spring:
  application:
    name: bookvoed

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/books-db
    username: postgres
    password: postgres

    flyway:
      enabled: true
      locations: classpath:db/migration


  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class: thread