CREATE TABLE IF NOT EXISTS books
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_code varchar(50)  NOT NULL UNIQUE ,
    title       varchar(200) NOT NULL,
    brand       varchar(50)  NOT NULL,
    year        INT          NOT NULL,
    stock       INTEGER,
    price       NUMERIC(10, 2),

    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



